spring.application.name=springbootAssessment2

spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment_2
spring.datasource.username=postgres
spring.datasource.password=shubham
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

